### ISSUE TITLE
NTR: Nautical miles

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/P06#24]
Hi there, 

I'm hoping to get **nautical miles** added as a unit of measurement to P06, or at least bring it up for discussion:

### **Sources/references**: 
https://www.marineinsight.com/guidelines/nautical-mile-knot-units-used-sea/
https://science.howstuffworks.com/innovation/science-questions/question79.htm

### **Mapping to external terminologies** http://vocab.nerc.ac.uk/collection/P06/current/UKNT/

Thanks in advance!

Cheers, Tim

**Comment by dr-shorthair** [comment]
Yeah - that is a curious omission, given that [nautical-miles-per-hour](http://vocab.nerc.ac.uk/collection/P06/current/UKNT/) is already there!

UCUM code: `[nmi_i]`

**Comment by roy-lowry** [comment]
@dr-shorthair P06 was built on an 'as required' basis rather than systematic population. The need for knots was driven by handling UK research vessel navigation files that reported several speeds/velocities in knots but distance travelled in km. We obviously never encountered any other data in BODC or CF that required the unit nautical miles.

Now, such a mixture of units coming from the ships could be considered curious but is probably just an example of design by committee!

**Comment by dr-shorthair** [comment]
Yep. That was what I had inferred. Sorry if my comment was taken as negative. 

In fact that is what I tell everyone about NVS - it is bottom up, and there is nothing there that isn't actually in use somewhere. OTOH the OM ontology has exhaustively enumerated all the scaled versions of many units all the way out to atto-seconds-squared ;-) https://github.com/HajoRijgersberg/OM/pull/44/files

**Comment by gwemon** [comment]
@danibodc could you add this unit in too please? It looks like it's been overlooked.

**Comment by danibodc** [comment]
A new P06 code has been created: NTML	

**Preferred label:** Nautical miles	
**Alternative label:** Nm
**Definition**: A unit of length used to measure distance at sea, equivalent to 1852 standard SI units of length (metres).

It will be published live on the NVS from 0730 UTC tomorrow morning.
