### ISSUE TITLE
why are the definitions "unavailable"?

### ISSUE THREAD

**Issue by ymgan** [nvs-vocabs/P06#51]
Hi,

May I know why are there so many units with definition "unavailable" at https://vocab.nerc.ac.uk/search_nvs/P06/ ? Is this normal?

<img width="958" alt="Screenshot 2023-10-21 at 11 01 58" src="https://github.com/nvs-vocabs/P06/assets/11754081/5e273931-1a7d-4702-a470-2e144e4c65ce">

**Comment by gwemon** [comment]
Hi @ymgan this is because we have not yet managed the time to populate them. As you can see from the date on the right hand side, these units were added a few years ago when we did not yet have an established practice of writing down definitions. Nowadays we would add definitions alongside new terms. Definitions can be proposed if required. Was there any  that you needed in particular?

**Comment by ymgan** [comment]
Thanks @gwemon !! I understand. I opened this ticket because I noticed this when I wanted to recommend someone from the Humboldt community to use BODC and eMoF at some point. I don't need anything in particular.
